In [35]:
#NumPy: NumPy is one of the fundamental packages for scientific computing in Python.
import numpy as np
x = np.array([[1,2,3],[4,5,6]])
print("X:\n{}".format(x))

X:
[[1 2 3]
 [4 5 6]]


In [36]:
import numpy as np
print("Numpy Version:", np.__version__)
print(np.show_config())


Numpy Version: 1.21.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE41,POPCNT,SSE42,AVX,F16C,FMA3,AVX2
    not found = 

In [37]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [38]:
# more than one dimensions 
import numpy as np

a = np.array([1,2,3])
print(a)

a = np.array([[1,2,3], [4,5,6]])

print(a)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [39]:
#minimum dimensions 

import numpy as np
a =np.array([1,2,3,4,5], ndmin =3)
print(a)

[[[1 2 3 4 5]]]


In [40]:
## dtype parameter 
import numpy as np
a = np.array([1,2,3], dtype = complex)

print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [41]:
# using array-scalar type 
import numpy as np
dt = np.dtype(np.int64)
print(dt)


int64


In [42]:
## using endian notation

import numpy as np
dt = np.dtype('i4')

print(dt)

int32


In [43]:
## first create structured data type
import numpy as np
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype=dt)
print(a)

[(10,) (20,) (30,)]


In [44]:
## file name can be used to access content of age column 
import numpy as np
dt = np.dtype([('age', np.int8)])
a = np.array([(10,), (20,), (30,)], dtype = dt)
print (a['age'])

[10 20 30]


In [1]:
from sklearn import model_selection
from sklearn.ensemble import AdaBoostClassifier
from sklearn import svm
from xgboost import XGBClassifier 


In [ ]:
i