In [7]:
import numpy as np 
distance =[10,15,17,26]
time = [.30, .47, .55, 1.20]


In [8]:
np_distance =np.array(distance)
np_time = np.array(time)
speed=np_distance/np_time
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

Numpy with ndarray

In [9]:
import numpy as np 

In [10]:
#1st nympy array
first_np_array =np.array([1,2,3,4,5])


In [11]:
#print numpy array
print(first_np_array)

[1 2 3 4 5]


In [12]:
array_eye = np.eye(3,3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#array with zero
array_with_zero = np.zeros([3,3])
array_with_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#array with one
array_with_one= np.ones([3,3])
array_with_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
#array with empty
array_with_empty=np.empty((2,2))
array_with_empty

array([[33.33333333, 31.91489362],
       [30.90909091, 21.66666667]])

In [16]:
#Array with custome value
array_cus=np.full((3,3),6)
array_cus

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [17]:
#array with order method
np_array =np.arange(12)
print(np_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
#reshape method to change/create array
np_array.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
# linspace for linearLy (equal) spaced data elements
np_linspace= np.linspace(1,6,5)
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [20]:
#one dimensional array
oneD_array=np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [21]:
#two dimensional array
TwoD_arry= oneD_array.reshape(3,5)
print(TwoD_arry)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [22]:
#Three dimensional array
threeD_array=np.arange(27).reshape(3,3,3)
print(threeD_array)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [23]:
#Some mathematical operation in numpy
np.add(10,25), np.subtract(50,25), np.divide(25,5), np.multiply(4,5)

(35, 25, 5.0, 20)

In [24]:
#ndarray multiplication
#create ndarray which contrains number of hrs worked for 5 days
#hourly rate is 15 USD

daily_wage =np.array([10,7,8,9,6])*15
daily_wage

array([150, 105, 120, 135,  90])

In [25]:
np.sum(daily_wage)

600

In [26]:
#Comparison Operation
#create weekly hrs ndarray

weekly_hrs = np.array([56,49,63,42,54])
weekly_hrs


array([56, 49, 63, 42, 54])

In [27]:
weekly_hrs[weekly_hrs<50], weekly_hrs[weekly_hrs>50], weekly_hrs[weekly_hrs !=56]

(array([49, 42]), array([56, 63, 54]), array([49, 63, 42, 54]))

In [28]:
arr1 = np.array([12,3,4,6,7,8,9,2,1])
arr1

array([12,  3,  4,  6,  7,  8,  9,  2,  1])

In [29]:
arr2=arr1.reshape(3,3)
arr2

array([[12,  3,  4],
       [ 6,  7,  8],
       [ 9,  2,  1]])

In [30]:
arr2.ravel()

array([12,  3,  4,  6,  7,  8,  9,  2,  1])

In [31]:
arr2[1: , 1:]

array([[7, 8],
       [2, 1]])

In [32]:
arr3= arr2 * arr2
arr3

array([[144,   9,  16],
       [ 36,  49,  64],
       [ 81,   4,   1]])

In [33]:
arr2.mean(), arr2.std()

(5.777777777777778, 3.3920750049941666)

Example #1
The following is the grade data of ten students. Create a code using NumPy that calcuate and report their grade average.
Names = ['Jevon', 'Dawn', 'Kayleigh', 'Jadene', 'Kennedy', 'Kaydee', 'Ansh', 'Flynn', 'Kier', 'Clarence']
Math_grades = [80, 50, 60, 70, 60, 100, 70, 70, 60, 70]
Science_grades = [90, 80, 50, 50, 60, 50, 90, 70, 80, 80]
History_grades = [60, 90, 50, 90, 100, 100, 100, 100, 90, 70]

In [3]:
import numpy as np
Names = ['Jevon', 'Dawn', 'Kayleigh', 'Jadene', 'Kennedy', 'Kaydee', 'Ansh', 'Flynn', 'Kier', 'Clarence']
Math_grades = [80, 50, 60, 70, 60, 100, 70, 70, 60, 70]
Science_grades = [90, 80, 50, 50, 60, 50, 90, 70, 80, 80]
History_grades = [60, 90, 50, 90, 100, 100, 100, 100, 90, 70]

In [5]:
#Create empty array
Average_grades = np.zeros(10)
print(Average_grades)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#Calculating average using np

for i, name in enumerate(Names):
    Average_grades[i]=np.mean([Math_grades[i],Science_grades[i],History_grades[i]])
print(Average_grades)    

[76.66666667 73.33333333 53.33333333 70.         73.33333333 83.33333333
 86.66666667 80.         76.66666667 73.33333333]


In [24]:
for i, name in enumerate(Names):
    avr=("{}'s Average Grade is:{}".format(name, Average_grades[i]))
    print(avr)  

Jevon's Average Grade is:76.66666666666667
Dawn's Average Grade is:73.33333333333333
Kayleigh's Average Grade is:53.333333333333336
Jadene's Average Grade is:70.0
Kennedy's Average Grade is:73.33333333333333
Kaydee's Average Grade is:83.33333333333333
Ansh's Average Grade is:86.66666666666667
Flynn's Average Grade is:80.0
Kier's Average Grade is:76.66666666666667
Clarence's Average Grade is:73.33333333333333


In [9]:
#Creating report

for i, name in enumerate(Names):
    print("{}'s Average Grade is:{}".format(name, Average_grades[i]))

Jevon's Average Grade is:76.66666666666667
Dawn's Average Grade is:73.33333333333333
Kayleigh's Average Grade is:53.333333333333336
Jadene's Average Grade is:70.0
Kennedy's Average Grade is:73.33333333333333
Kaydee's Average Grade is:83.33333333333333
Ansh's Average Grade is:86.66666666666667
Flynn's Average Grade is:80.0
Kier's Average Grade is:76.66666666666667
Clarence's Average Grade is:73.33333333333333


In [10]:
#Checking linspace
np.linspace(0,1,21)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [11]:
np.linspace(10,1000,100)

array([  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,
        100.,  110.,  120.,  130.,  140.,  150.,  160.,  170.,  180.,
        190.,  200.,  210.,  220.,  230.,  240.,  250.,  260.,  270.,
        280.,  290.,  300.,  310.,  320.,  330.,  340.,  350.,  360.,
        370.,  380.,  390.,  400.,  410.,  420.,  430.,  440.,  450.,
        460.,  470.,  480.,  490.,  500.,  510.,  520.,  530.,  540.,
        550.,  560.,  570.,  580.,  590.,  600.,  610.,  620.,  630.,
        640.,  650.,  660.,  670.,  680.,  690.,  700.,  710.,  720.,
        730.,  740.,  750.,  760.,  770.,  780.,  790.,  800.,  810.,
        820.,  830.,  840.,  850.,  860.,  870.,  880.,  890.,  900.,
        910.,  920.,  930.,  940.,  950.,  960.,  970.,  980.,  990.,
       1000.])

Example 2
We are interested in finding the value(s) that holds the following mathematical statement.
x^2-5x+6=0
And imagine that we don’t know that the statement can be simplified easily to find either -1 or +1 will hold the statement.
x^2-5x+6=(x-2)(x-3)
so we would like to use NumPy to try out any values between -100 and 100 and see what the answer is.

In [18]:
candidates =np.linspace(-100,100,201)
#candidate

for candidate in candidates:
    if(candidate**2 -5*candidate+6 ==0):
        print("Just found a possible answer:{}".format(candidate))

Just found a possible answer:2.0
Just found a possible answer:3.0


In [27]:
! pip install opencv-python

In [28]:
import cv2