In [8]:
import numpy as np 
distance =[10,15,17,26]
time = [.30, .47, .55, 1.20]


In [10]:
np_distance =np.array(distance)
np_time = np.array(time)
speed=np_distance/np_time
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

Numpy with ndarray

In [2]:
import numpy as np 

In [10]:
#1st nympy array
first_np_array =np.array([1,2,3,4,5])


In [11]:
#print numpy array
print(first_np_array)

[1 2 3 4 5]


In [4]:
array_eye = np.eye(3,3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#array with zero
array_with_zero = np.zeros([3,3])
array_with_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
#array with one
array_with_one= np.ones([3,3])
array_with_one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
#array with empty
array_with_empty=np.empty((2,2))
array_with_empty

array([[33.33333333, 31.91489362],
       [30.90909091, 21.66666667]])

In [6]:
#Array with custome value
array_cus=np.full((3,3),6)
array_cus

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [25]:
#array with order method
np_array =np.arange(12)
print(np_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
#reshape method to change/create array
np_array.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
# linspace for linearLy (equal) spaced data elements
np_linspace= np.linspace(1,6,5)
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [33]:
#one dimensional array
oneD_array=np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [35]:
#two dimensional array
TwoD_arry= oneD_array.reshape(3,5)
print(TwoD_arry)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
#Three dimensional array
threeD_array=np.arange(27).reshape(3,3,3)
print(threeD_array)

In [14]:
#Some mathematical operation in numpy
np.add(10,25), np.subtract(50,25), np.divide(25,5), np.multiply(4,5)

(35, 25, 5.0, 20)

In [15]:
#ndarray multiplication
#create ndarray which contrains number of hrs worked for 5 days
#hourly rate is 15 USD

daily_wage =np.array([10,7,8,9,6])*15
daily_wage

array([150, 105, 120, 135,  90])

In [16]:
np.sum(daily_wage)

600

In [18]:
#Comparison Operation
#create weekly hrs ndarray

weekly_hrs = np.array([56,49,63,42,54])
weekly_hrs


array([56, 49, 63, 42, 54])

In [22]:
weekly_hrs[weekly_hrs<50], weekly_hrs[weekly_hrs>50], weekly_hrs[weekly_hrs !=56]

(array([49, 42]), array([56, 63, 54]), array([49, 63, 42, 54]))

In [23]:
arr1 = np.array([12,3,4,6,7,8,9,2,1])
arr1

array([12,  3,  4,  6,  7,  8,  9,  2,  1])

In [25]:
arr2=arr1.reshape(3,3)
arr2

array([[12,  3,  4],
       [ 6,  7,  8],
       [ 9,  2,  1]])

In [26]:
arr2.ravel()

array([12,  3,  4,  6,  7,  8,  9,  2,  1])

In [28]:
arr2[1: , 1:]

array([[7, 8],
       [2, 1]])

In [40]:
arr3= arr2 * arr2
arr3

array([[144,   9,  16],
       [ 36,  49,  64],
       [ 81,   4,   1]])

In [47]:
arr2.mean(), arr2.std()

(5.777777777777778, 3.3920750049941666)