Adult Dataset

Adult Dataset
"Census Income" dataset.

Number of Instances: 48842 Number of Attributes: 14 Date Donated: 1996-05-01 Missing Values?: Yes

Attributes:
Number of Attributes: 6 continuous, 8 nominal attributes

age: continuous.
workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
fnlwgt: continuous.
education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
education-num: continuous.
marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
sex: Female, Male.
capital-gain: continuous.
capital-loss: continuous.
hours-per-week: continuous.
native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
class: >50K, <=50K

In [12]:
#Read adult dataset
import pandas as pd 
import numpy as np
adult_df = pd.read_csv("adult.csv")
adult_df.head()

age         workclass  fnlwgt  education  education-num  \
0    2         State-gov   77516  Bachelors             13   
1    3  Self-emp-not-inc   83311  Bachelors             13   
2    2           Private  215646    HS-grad              9   
3    3           Private  234721       11th              7   
4    1           Private  338409  Bachelors             13   

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male   
1  Married-civ-spouse    Exec-managerial        Husband  White    Male   
2            Divorced  Handlers-cleaners  Not-in-family  White    Male   
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male   
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female   

   capitalgain  capitalloss  hoursperweek native-country  class  
0            1            0             2  United-States  <=50K  
1            0            0             0  United-States  <=50K  
2            0            0             2  United-States  <=50K  
3            0            0             2  United-States  <=50K  
4            0            0             2           Cuba  <=50K

In [3]:
#Checking shape
adult_df.shape

(48842, 15)

In [5]:
#checking the type
print(type(adult_df))
print(type(adult_df["age"]))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [10]:
#checking indexes
adult_df.loc[0].index

Index(['age', 'workclass', 'fnlwgt', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capitalgain', 'capitalloss', 'hoursperweek', 'native-country',
       'class'],
      dtype='object')

In [11]:
adult_df.age.index

RangeIndex(start=0, stop=48842, step=1)

In [15]:
#Set index
adult_df.set_index(np.arange(10000,58842), inplace=True)

In [16]:
adult_df.set_index(np.arange(10000,58842))

age         workclass  fnlwgt  education  education-num  \
10000    2         State-gov   77516  Bachelors             13   
10001    3  Self-emp-not-inc   83311  Bachelors             13   
10002    2           Private  215646    HS-grad              9   
10003    3           Private  234721       11th              7   
10004    1           Private  338409  Bachelors             13   
...    ...               ...     ...        ...            ...   
58837    2           Private  215419  Bachelors             13   
58838    4               NaN  321403    HS-grad              9   
58839    2           Private  374983  Bachelors             13   
58840    2           Private   83891  Bachelors             13   
58841    1      Self-emp-inc  182148  Bachelors             13   

           marital-status         occupation    relationship  \
10000       Never-married       Adm-clerical   Not-in-family   
10001  Married-civ-spouse    Exec-managerial         Husband   
10002            Divorced  Handlers-cleaners   Not-in-family   
10003  Married-civ-spouse  Handlers-cleaners         Husband   
10004  Married-civ-spouse     Prof-specialty            Wife   
...                   ...                ...             ...   
58837            Divorced     Prof-specialty   Not-in-family   
58838             Widowed                NaN  Other-relative   
58839  Married-civ-spouse     Prof-specialty         Husband   
58840            Divorced       Adm-clerical       Own-child   
58841  Married-civ-spouse    Exec-managerial         Husband   

                     race     sex  capitalgain  capitalloss  hoursperweek  \
10000               White    Male            1            0             2   
10001               White    Male            0            0             0   
10002               White    Male            0            0             2   
10003               Black    Male            0            0             2   
10004               Black  Female            0            0             2   
...                   ...     ...          ...          ...           ...   
58837               White  Female            0            0             2   
58838               Black    Male            0            0             2   
58839               White    Male            0            0             3   
58840  Asian-Pac-Islander    Male            2            0             2   
58841               White    Male            0            0             3   

      native-country  class  
10000  United-States  <=50K  
10001  United-States  <=50K  
10002  United-States  <=50K  
10003  United-States  <=50K  
10004           Cuba  <=50K  
...              ...    ...  
58837  United-States  <=50K  
58838  United-States  <=50K  
58839  United-States  <=50K  
58840  United-States  <=50K  
58841  United-States   >50K  

[48842 rows x 15 columns]

In [17]:
adult_df.iloc[2].loc["education"]

'HS-grad'

In [18]:
adult_df.education.loc[10002]

'HS-grad'

In [19]:
adult_df['education'].iloc[2]

'HS-grad'

Slicing

In [22]:
my_array = np.array([[34,12,24,23],[23,67,54,34],[56,43,76,12],[12,89,65,43]])
my_array

array([[34, 12, 24, 23],
       [23, 67, 54, 34],
       [56, 43, 76, 12],
       [12, 89, 65, 43]])

In [23]:
my_array[1,1]

67

In [27]:
my_array[1,:]

array([23, 67, 54, 34])

In [28]:
my_array[:,1]

array([12, 67, 43, 89])

In [29]:
my_array[1:3,:]

array([[23, 67, 54, 34],
       [56, 43, 76, 12]])

In [30]:
my_array

array([[34, 12, 24, 23],
       [23, 67, 54, 34],
       [56, 43, 76, 12],
       [12, 89, 65, 43]])

In [35]:
my_array[:,1:]

array([[12, 24, 23],
       [67, 54, 34],
       [43, 76, 12],
       [89, 65, 43]])

In [37]:
my_array[1:3,0:2]

array([[23, 67],
       [56, 43]])

In [38]:
adult_df.loc[:,'education':'occupation']

education  education-num      marital-status         occupation
10000  Bachelors             13       Never-married       Adm-clerical
10001  Bachelors             13  Married-civ-spouse    Exec-managerial
10002    HS-grad              9            Divorced  Handlers-cleaners
10003       11th              7  Married-civ-spouse  Handlers-cleaners
10004  Bachelors             13  Married-civ-spouse     Prof-specialty
...          ...            ...                 ...                ...
58837  Bachelors             13            Divorced     Prof-specialty
58838    HS-grad              9             Widowed                NaN
58839  Bachelors             13  Married-civ-spouse     Prof-specialty
58840  Bachelors             13            Divorced       Adm-clerical
58841  Bachelors             13  Married-civ-spouse    Exec-managerial

[48842 rows x 4 columns]

In [39]:
adult_df.sort_values('education-num').reset_index().iloc[1:48842:3617]

index  age         workclass  fnlwgt     education  education-num  \
1      49615    4  Self-emp-not-inc  161552     Preschool              1   
3618   22593    2  Self-emp-not-inc  207202          10th              6   
7235   45728    1           Private  339738       HS-grad              9   
10852  46944    2           Private  124111       HS-grad              9   
14469  33106    3      Self-emp-inc  162439       HS-grad              9   
18086  16494    2           Private  162256       HS-grad              9   
21703  12454    3           Private  207058       HS-grad              9   
25320  12990    0           Private   44064  Some-college             10   
28937  33649    2           Private  390368  Some-college             10   
32554  52143    1           Private   79702  Some-college             10   
36171  33036    2  Self-emp-not-inc  133299    Assoc-acdm             12   
39788  32602    3           Private  194259     Bachelors             13   
43405  42241    2         State-gov  231013     Bachelors             13   
47022  22108    1           Private  294064       Masters             14   

           marital-status        occupation    relationship   race     sex  \
1                 Widowed   Exec-managerial   Not-in-family  White  Female   
3618   Married-civ-spouse   Farming-fishing         Husband  White    Male   
7235   Married-civ-spouse  Transport-moving  Other-relative  Black    Male   
10852            Divorced      Adm-clerical       Unmarried  White  Female   
14469  Married-civ-spouse   Exec-managerial         Husband  White    Male   
18086            Divorced   Exec-managerial       Unmarried  White  Female   
21703            Divorced      Adm-clerical       Unmarried  White  Female   
25320       Never-married    Prof-specialty       Own-child  White    Male   
28937  Married-civ-spouse             Sales         Husband  Black    Male   
32554       Never-married      Adm-clerical  Other-relative  Black    Male   
36171  Married-civ-spouse  Transport-moving         Husband  White    Male   
39788            Divorced      Tech-support       Unmarried  White  Female   
43405            Divorced   Protective-serv   Not-in-family  White    Male   
47022  Married-civ-spouse   Exec-managerial         Husband  White    Male   

       capitalgain  capitalloss  hoursperweek native-country  class  
1                0            0             3  United-States  <=50K  
3618             0            0             3  United-States  <=50K  
7235             0            0             2  United-States  <=50K  
10852            0            0             1  United-States  <=50K  
14469            0            0             4  United-States   >50K  
18086            0            0             2  United-States  <=50K  
21703            0            0             2  United-States  <=50K  
25320            0            0             1  United-States  <=50K  
28937            4            0             4  United-States   >50K  
32554            0            0             2  United-States  <=50K  
36171            0            0             2  United-States  <=50K  
39788            0            0             2  United-States  <=50K  
43405            0            0             2  United-States  <=50K  
47022            0            0             3         France  <=50K