In [1]:
import scipy 
from scipy.integrate import quad

In [2]:
def integrateFunction(x):
    return x

In [3]:
quad(integrateFunction, 0,1)

(0.5, 5.551115123125783e-15)

In [7]:
def integrateFN(x, a, b):
    return x*a+b
a=3
b=2

In [8]:
quad(integrateFN,0,1, args=(a,b))

(3.5, 3.885780586188048e-14)

In [9]:
#General integration
import scipy.integrate as integrate 


In [10]:
def f(x,y):
    return x+y

integrate.dblquad(f, 0, 1,lambda x:0, lambda x:2)    

(3.0, 4.436070580899685e-14)

In [11]:
#Optimization function

import numpy as np
from scipy import optimize

In [12]:
def f(x):
    return x**2 + 5*np.sin(x)

In [14]:
nimimulvalue = optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [17]:
minimavaluewithoutopt= optimize.minimize(f,x0=2,method='bfgs')
minimavaluewithoutopt

      fun: -3.2463942726915196
 hess_inv: array([[0.15445831]])
      jac: array([-4.47034836e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [18]:
#Optimize the root function
import numpy as np
from scipy.optimize import root 
def rootfunc(x):
    return x + 3.5 * np.cos(x)

In [ ]:
rootValue = root(rootfunc, 0.3)
rootValue

In [ ]:
#Solve linear system
#2x+3y+z=21; -x+5y+4z=9; 3x+2y+9z=6

In [20]:
import numpy as np
from scipy import linalg

In [21]:
numArray =np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [22]:
numArrayValue=np.array([21,9,6])

In [23]:
linalg.solve(numArray,numArrayValue)

array([ 4.95,  4.35, -1.95])

In [26]:
#Calculate eigenvalues and eigenvectors
import numpy as np
from scipy import linalg

In [29]:
#test data matrix - (rating on scale of 10)
test_rating_data = np.array([[5,8],[7,9]])
eigenValues, eigenVector = linalg.eig(test_rating_data)
firsteigen, secondeigen = eigenValues

In [31]:
#print eigenvalues(first and second eigenValues)
print(firsteigen,secondeigen)

(-0.745966692414834+0j) (14.745966692414834+0j)


In [33]:
#print first eigenVector and second eigenVector

print(eigenVector[0:,0])
print(eigenVector[0:,1])

[-0.81220939  0.58336601]
[-0.63447346 -0.77294465]


In [35]:
#Statistical sub-package 
from scipy.stats import norm

In [37]:
norm.rvs(loc=0,scale=1, size=10)

array([-0.15517742,  0.7581832 ,  0.25695571,  0.52738212, -0.5452596 ,
       -1.05993938,  1.00688775,  0.260661  , -1.97924501, -0.1635768 ])

In [39]:
norm.cdf(5, loc=0,scale=1)

0.9999997133484281

In [40]:
norm.pdf(9, loc=0, scale=1)

1.0279773571668917e-18

In [ ]:
norm.rvs(size=1000)


In [41]:
import numpy as np
from scipy import linalg

In [43]:
TFArray =np.array([[1,1],[4,9]])
TFArray

array([[1, 1],
       [4, 9]])

In [46]:
TFArrayValue=np.array([30,150])
TFArrayValue

array([ 30, 150])

In [47]:
linalg.solve(TFArray,TFArrayValue)

array([24.,  6.])

Problem:
Use SciPy to declare 20 random values for random values and perform the following:
1. CDF – Cumulative Distribution Function for a random variable 10
2. PDF – Probability Density Function for a random variable 14.

In [51]:
from scipy.stats import norm
norm.rvs(loc=0,scale=1, size=20)

array([ 1.21263905, -0.09902193,  0.28464487,  1.11822412,  0.07767789,
        0.96209169,  0.66046722,  1.03644335,  2.4596795 , -0.00477911,
        0.31941607, -0.68684342, -0.87435503, -1.22321658,  0.63415551,
       -0.03290638, -0.49057713, -2.24480144, -0.97707097, -0.22240001])

In [49]:
norm.cdf(10,loc=0,scale=1)

1.0

In [50]:
norm.pdf(14, loc=0,scale=1)

1.0966065593889713e-43